[features]
seeds = false
[programs.devnet]
solanotes = "BkdhfUz2R7hhvt9PVoTbS8zGf3ztPHhDDGFm4zPrwuvV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/matheus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 10000000 tests/**/*.ts"
